//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewLanguageLearning_Admin.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HLL_LessonsGrammar
    {
        public string LessonsGrammarId { get; set; }
        public string fkLessonId { get; set; }
        public string fkGrammarId { get; set; }
        public Nullable<int> GrammarPoint1 { get; set; }
        public Nullable<int> GrammarPoint2 { get; set; }
        public Nullable<int> GrammarPoint3 { get; set; }
        public Nullable<int> GrammarPoint4 { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
